### ISSUE TITLE
question about Perfectly obfuscated gates

### ISSUE THREAD

**Issue by themighty1** [chart21/CRGC#2]
Hi, thank you for this work.
Is it correct that when the README table shows 30% Perfectly obfuscated gates, it means that for the rest of the 70% of gates yao's GC would have to be used?

Do you have any suggestions about how one could increase the rate of Perfectly obfuscated gates? Would changing ordering of gates be effective? Would introducing dummy gates help? Or would it only deteriorate the rate?

**Comment by chart21** [comment]
Not quite, you can get a rough estimation (upper bound) of the number of reusable gates by taking the union (U) of gates on L1 U balanced gates U potentially passive gates (fixed +intermediary gates). I will add a function for this in the future.
For all other gates, Yao's GC needs to be used for provable leakage prevention.

Perfectly obfuscated gates is an outdated metric and does not include balanced gates and gates on level 1. I will replace that soon by the above.

**Comment by themighty1** [comment]
Thanks. It makes more sense now. So, the metric that I actually need is reusable gates count.

Am I understandig correctly that in my specific use case where G and E input their xor shares of the AES key and the first thing the circuit does is XOR the shares and then outputs an encrypted zero:

- there will be no fixed gates
- since there are no fixed gates then by definition there are no intermediary gates
- the amount or reusable gates will equal to XOR gates
- all AND gates will not be reusable
(we assume that all NOT gates were subsumed by the child XOR/AND gates)

Is my understanding correct?

**Comment by chart21** [comment]
Yes, your understanding is correct. This also means that all AND gates are potentially revealing gates.
